############################################################
# +------------------------------------------------------+ #
# |                       MagicLamps                     | #
# +------------------------------------------------------+ #
############################################################

#Config version - 0.3
#Developed by Kenny Williams | exload
#Website: http://arcanerealm.net/
#Forums: http://forums.arcanerealm.net/
#YouTube: http://www.youtube.com/mrcomputeranswers
#Questions, comments, or bugs, email me: kenny@vectorgaming.net

#Mcstats.org reporting. This information is harmless and simply provides me, the
#developer, with useful stats on this plugin.
mcstats: true

auto-update: true

#Do NOT mess with this. It WILL break the plugin. Seriously, it will.
config-version: 0.3
