name: MagicLamps
main: net.vectorgaming.magiclamps.MagicLamps
version: 0.3.3
author: exload
website: http://arcanerealm.net
description: MagicLamps - Creating lamps with no redstone

commands:
  mgl:
    description: MagicLamps base command